language: node_js
node_js:
  - "0.12"
  - "0.10"

services:
  - mongodb

install:
- npm install
- (cd examples/simple && npm install)
  
script:
- npm test
- (cd examples/simple && npm test)


env:
  - NODE_ENV=test"